/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Victor Henrich
 */
public class MainComponent extends javax.swing.JFrame {

    /**
     * Creates new form MainComponent
     */
    public MainComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItemColaborador = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemFornecedor = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemCliente = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jCheckBoxMenuItemCidade = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEndereco = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemBairro = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jCheckBoxMenuItemClasse = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemMarca = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemProduto = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setText("Cadastros");

        jMenu5.setText("Pessoas");

        jCheckBoxMenuItemColaborador.setText("Colaborador");
        jMenu5.add(jCheckBoxMenuItemColaborador);

        jCheckBoxMenuItemFornecedor.setText("Fornecedor");
        jMenu5.add(jCheckBoxMenuItemFornecedor);

        jCheckBoxMenuItemCliente.setText("Cliente");
        jMenu5.add(jCheckBoxMenuItemCliente);

        jMenu1.add(jMenu5);

        jMenu6.setText("Endereços");

        jCheckBoxMenuItemCidade.setText("Cidade");
        jMenu6.add(jCheckBoxMenuItemCidade);

        jCheckBoxMenuItemEndereco.setText("Endereço");
        jMenu6.add(jCheckBoxMenuItemEndereco);

        jCheckBoxMenuItemBairro.setText("Bairro");
        jMenu6.add(jCheckBoxMenuItemBairro);

        jMenu1.add(jMenu6);

        jMenu7.setText("Produtos");

        jCheckBoxMenuItemClasse.setText("Classe");
        jMenu7.add(jCheckBoxMenuItemClasse);

        jCheckBoxMenuItemMarca.setText("Marca");
        jMenu7.add(jCheckBoxMenuItemMarca);

        jCheckBoxMenuItemProduto.setText("Produto");
        jMenu7.add(jCheckBoxMenuItemProduto);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Financeiro");

        jMenu3.setText("Vendas");
        jMenu2.add(jMenu3);

        jMenu4.setText("Compras");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainComponent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemBairro;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemCidade;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemClasse;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemCliente;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemColaborador;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEndereco;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemFornecedor;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemMarca;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
